name: Build & Test Maven Project
on:
  push:
  schedule:
    - cron: '0 15 * * *' # daily at 3pm
jobs:
  build-and-test:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 24
          java-package: jdk
          cache: maven

      - name: Build project
        timeout-minutes: 15
        continue-on-error: true
        run: ./mvnw verify --no-transfer-progress
